import { localDate } from "./trainingData.js";
const definitions = [
  [
    "handstand",
    "Parallette handstand",
    "skill",
    "Shoulders, triceps",
    "Balance practice with a neutral wrist",
    "Stack shoulders over hands; push tall; keep ribs tucked",
    "Pike hold",
    "Longer balanced holds",
    "parallettes",
    "wrist, shoulder",
  ],
  [
    "incline",
    "Low-incline machine press",
    "weighted",
    "Upper chest",
    "Upper-chest strength",
    "Keep shoulders supported; control the lowering",
    "Lighter machine press",
    "Small load increase",
    "machine",
    "shoulder, elbow",
  ],
  [
    "dbpress",
    "Neutral-grip dumbbell press",
    "weighted",
    "Chest, triceps",
    "Press with a neutral grip",
    "Keep wrists straight; lower under control",
    "Lighter dumbbells",
    "Small load increase",
    "dumbbells",
    "wrist, shoulder",
  ],
  [
    "fly",
    "Low-to-high cable fly",
    "weighted",
    "Upper chest",
    "Upper-chest isolation",
    "Soft elbows; sweep upward without shrugging",
    "Shorter comfortable range",
    "More controlled range",
    "cable",
    "shoulder",
  ],
  [
    "lateral",
    "Lateral raise",
    "weighted",
    "Side delts",
    "Shoulder strength",
    "Lead with elbows; avoid swinging",
    "Lighter load",
    "Small load increase",
    "dumbbells",
    "shoulder",
  ],
  [
    "pressdown",
    "Cable pressdown",
    "weighted",
    "Triceps",
    "Elbow extension strength",
    "Keep elbows still and wrists neutral",
    "Lighter band",
    "Small load increase",
    "cable or band",
    "elbow",
  ],
  [
    "rotation",
    "Cable/band external rotation",
    "weighted",
    "Rotator cuff",
    "Shoulder preparation",
    "Keep elbow stable; rotate slowly",
    "Lighter band",
    "More controlled range",
    "cable or band",
    "shoulder",
  ],
  [
    "lever",
    "Tuck front lever",
    "hold",
    "Lats, core",
    "Front-lever skill and straight-arm preparation",
    "Depress scapulae; keep elbows straight and tuck stable",
    "Feet-supported tuck",
    "Advanced tuck",
    "bar or rings",
    "shoulder, elbow",
  ],
  [
    "pullup",
    "Strict pull-up",
    "bodyweight",
    "Lats, upper back",
    "Strict pulling strength",
    "Start controlled; no kip; use consistent range",
    "Assisted pull-up",
    "Weighted pull-up after 3 × 6–8 clean reps",
    "bar",
    "elbow, shoulder",
  ],
  [
    "pulldown",
    "Single-arm cable pulldown",
    "weighted",
    "Lower lats",
    "Lower-lat emphasis",
    "Draw elbow toward hip; avoid trunk rotation",
    "Lighter load",
    "Small load increase",
    "cable",
    "shoulder",
  ],
  [
    "row",
    "High-to-low seated cable row",
    "weighted",
    "Upper lats, upper back",
    "Upper-lat and upper-back emphasis",
    "Stable torso; pull elbows back without shrugging",
    "Lighter load",
    "Small load increase",
    "cable",
    "shoulder",
  ],
  [
    "facepull",
    "Face pull",
    "weighted",
    "Rear delts, upper back",
    "Scapular control",
    "Pull toward face; avoid arching",
    "Lighter band",
    "More controlled range",
    "cable",
    "shoulder",
  ],
  [
    "curl",
    "Curl",
    "weighted",
    "Biceps",
    "Elbow flexor strength",
    "Keep elbows still; no swinging",
    "Lighter load",
    "Small load increase",
    "dumbbells",
    "elbow",
  ],
  [
    "extension",
    "Back extension",
    "bodyweight",
    "Spinal erectors, glutes",
    "Posterior-chain endurance",
    "Hinge at hips; stop at a neutral spine",
    "Shorter comfortable range",
    "Controlled reps",
    "back extension bench",
    "hip",
  ],
  [
    "scapular",
    "Scapular pull-up",
    "bodyweight",
    "Lower traps, lats",
    "Scapular preparation",
    "Straight elbows; move only shoulder blades",
    "Feet-supported scapular pull",
    "Controlled range",
    "bar",
    "shoulder",
  ],
  [
    "slide",
    "Serratus wall slide",
    "bodyweight",
    "Serratus anterior",
    "Upward scapular rotation",
    "Slide forearms upward without flaring ribs",
    "Shorter range",
    "Controlled range",
    "wall",
    "shoulder",
  ],
  [
    "forearm",
    "Forearm pronation/supination",
    "weighted",
    "Forearms",
    "Forearm tendon preparation",
    "Support elbow; rotate slowly in a comfortable range",
    "Unloaded rotation",
    "Small load increase",
    "light dumbbell",
    "wrist, elbow",
  ],
  [
    "wrist",
    "Wrist isometric",
    "hold",
    "Forearms",
    "Wrist preparation",
    "Keep wrist neutral; use gentle tolerable resistance",
    "Less resistance",
    "Longer comfortable hold",
    "band",
    "wrist",
  ],
  [
    "straightarm",
    "Straight-arm cable pulldown",
    "weighted",
    "Lats",
    "Straight-arm preparation",
    "Keep elbows soft but fixed; do not arch",
    "Lighter band",
    "Controlled range",
    "cable",
    "shoulder, elbow",
  ],
  [
    "pallof",
    "Pallof press or hollow-body work",
    "bodyweight",
    "Core",
    "Anti-rotation and trunk control",
    "Keep ribs down; breathe throughout",
    "Shorter lever",
    "Longer controlled sets",
    "cable or mat",
    "trunk",
  ],
  [
    "rear",
    "Rear-delt fly",
    "weighted",
    "Rear delts",
    "Posterior shoulder strength",
    "Soft elbows; avoid shrugging",
    "Lighter load",
    "Small load increase",
    "dumbbells",
    "shoulder",
  ],
  [
    "hammer",
    "Hammer curl",
    "weighted",
    "Brachialis, forearms",
    "Neutral-grip elbow flexion",
    "Keep wrists neutral and elbows still",
    "Lighter load",
    "Small load increase",
    "dumbbells",
    "elbow, wrist",
  ],
  [
    "deadbug",
    "Dead bug or Pallof press",
    "bodyweight",
    "Core",
    "Trunk control",
    "Keep lower back stable; extend slowly",
    "Shorter limb reach",
    "Longer controlled sets",
    "mat or cable",
    "trunk",
  ],
];
export const seedExercises = definitions.map(
  ([
    id,
    name,
    type,
    muscles,
    purpose,
    cues,
    regressions,
    progressions,
    equipment,
    joints,
  ]) => ({
    id,
    name,
    type,
    muscles,
    purpose,
    cues,
    regressions,
    progressions,
    equipment,
    joints,
    secondary: "Trunk stabilizers",
    category:
      type === "skill" || type === "hold"
        ? "Calisthenics"
        : "Strength & preparation",
    pattern: /press|fly|raise/.test(id)
      ? "Push"
      : /pull|row|lever/.test(id)
        ? "Pull"
        : "Control",
    classification: ["skill", "hold"].includes(type) ? "Skill" : "Strength",
    unilateral: ["pulldown", "rotation", "forearm"].includes(id),
    mistakes: ["Lost position", "Shortened range", "Momentum"],
    reference: "",
    restrictions:
      id === "handstand"
        ? "Parallettes or securely placed dumbbells only. No floor handstands."
        : "Use a symptom-tolerant range; review increasing pain.",
    main: ["incline", "dbpress", "pullup", "pulldown", "row"].includes(id),
  }),
);
const p = (exerciseId, sets, min, max = min, minutes) => ({
  exerciseId,
  sets,
  min,
  max,
  rest: ["handstand", "lever", "pullup"].includes(exerciseId) ? 120 : 90,
  rir: 2,
  load: 0,
  ...(minutes ? { minutes, attemptsMax: minutes === "8–12" ? 8 : 6 } : {}),
});
export function seedState() {
  return {
    version: 1,
    exercises: structuredClone(seedExercises),
    plan: {
      name: "Two-week re-entry",
      start: localDate(),
      days: [
        {
          name: "Upper chest and push",
          exercises: [
            p("handstand", 5, 0, 0, "8–12"),
            p("incline", 3, 8, 10),
            p("dbpress", 2, 8, 12),
            p("fly", 3, 12, 15),
            p("lateral", 3, 12, 15),
            p("pressdown", 3, 10, 15),
            p("rotation", 2, 12, 15),
          ],
        },
        {
          name: "Pull strength and front lever",
          exercises: [
            p("handstand", 5, 0, 0, "8–10"),
            p("lever", 3, 5, 8),
            p("pullup", 3, 3),
            p("pulldown", 2, 8, 12),
            p("row", 3, 8, 12),
            p("facepull", 2, 12, 15),
            p("curl", 2, 10, 15),
            p("extension", 2, 10, 12),
          ],
        },
        {
          name: "Tendon, joint and core preparation",
          exercises: [
            p("handstand", 4, 0, 0, "6–10"),
            p("rotation", 2, 12, 15),
            p("scapular", 2, 6, 8),
            p("slide", 2, 10),
            p("forearm", 2, 12),
            p("wrist", 3, 15, 20),
            p("straightarm", 2, 12, 15),
            p("pallof", 3, 10),
          ],
        },
        {
          name: "Pull volume and front lever",
          exercises: [
            p("handstand", 5, 0, 0, "8–10"),
            p("lever", 3, 5, 8),
            p("pullup", 4, 2, 3),
            p("row", 3, 10, 12),
            p("pulldown", 2, 10, 12),
            p("rear", 3, 12, 15),
            p("hammer", 2, 10, 12),
            p("extension", 2, 10, 12),
            p("deadbug", 3, 10),
          ],
        },
        ...["Friday", "Saturday", "Sunday"].map(() => ({
          name: "Recovery / rest",
          exercises: [],
        })),
      ],
    },
    sessions: [],
    checkins: {},
    settings: {
      phase: 1,
      prStandard: "Clean",
      wristAssessed: false,
      dipsPainFree: false,
    },
    recovery: { enabled: true, notes: "" },
  };
}
